require "options"
require "keymaps"
require "lsp-setup"

require "plugins.mini"
require "plugins.snacks"
require "plugins.yazi"
require "plugins.catppuccin"
require "plugins.conform"
require "plugins.lint"
require "plugins.codesnap"
require "plugins.treesitter"
require "plugins.cmp"
require "plugins.lualine"
require "plugins.noice"
-- require "plugins.tailwind-tools"
