require "options"
require "keymaps"

require "plugins.mini"
require "plugins.snacks"
require "plugins.yazi"
require "plugins.catppuccin"
require "plugins.conform"
require "plugins.lint"
require "plugins.none-ls"
require "plugins.codesnap"
require "plugins.treesitter"
require "plugins.lspconfig"
require "plugins.cmp"
require "plugins.hover"
require "plugins.tailwind-tools"
